# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificacoes', models.ManyToManyField(related_name='funcionarios_qualificados', to='equipamento.Equipamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaResponsavel',
            fields=[
                ('responsavel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Responsavel')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=20)),
            ],
            bases=('core.responsavel',),
        ),
        migrations.CreateModel(
            name='TecnicoResponsavel',
            fields=[
                ('responsavel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Responsavel')),
                ('qualificacoes', models.ManyToManyField(related_name='tecnicos_qualificados', to='equipamento.Equipamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.responsavel',),
        ),
    ]
