# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PV', 'Preventiva'), ('OT', 'Outra')], default='PV', max_length=2)),
                ('date', models.DateTimeField(verbose_name='date realized')),
            ],
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_freq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment'),
        ),
    ]
