# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20171120_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='contract',
        ),
        migrations.AddField(
            model_name='contract',
            name='equipment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='equipment.Equipment'),
            preserve_default=False,
        ),
    ]
