# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('equipment', '0005_auto_20171120_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='id',
        ),
        migrations.AddField(
            model_name='equipment',
            name='sector',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='location.Sector'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contract', serialize=False, to='equipment.Equipment'),
        ),
    ]
