# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0006_auto_20171120_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identity_type', models.CharField(choices=[('CPF', 'CPF'), ('CRM', 'CRM')], default='CPF', max_length=3)),
                ('identity', models.CharField(max_length=50)),
                ('qualifications', models.ManyToManyField(related_name='functionaries_qualified', to='equipment.Equipment')),
            ],
        ),
    ]
