# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('qualificacoes', models.ManyToManyField(related_name='qualificados', to='equipamento.Equipamento')),
            ],
        ),
    ]
