# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200)),
                ('data_realizada', models.DateTimeField(null=True, verbose_name='data realizada')),
            ],
        ),
        migrations.CreateModel(
            name='Qualificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CA', 'Calibrar'), ('MA', 'Realizar manutenção')], default='CA', max_length=2)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacoes', to='equipamento.Equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaResponsavel',
            fields=[
                ('responsavel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manutencao.Responsavel')),
                ('cnpj', models.CharField(max_length=20)),
            ],
            bases=('manutencao.responsavel',),
        ),
        migrations.CreateModel(
            name='ManutencaoCalibragem',
            fields=[
                ('manutencao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manutencao.Manutencao')),
            ],
            bases=('manutencao.manutencao',),
        ),
        migrations.CreateModel(
            name='ManutencaoCorretiva',
            fields=[
                ('manutencao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manutencao.Manutencao')),
            ],
            bases=('manutencao.manutencao',),
        ),
        migrations.CreateModel(
            name='ManutencaoPreventiva',
            fields=[
                ('manutencao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manutencao.Manutencao')),
                ('data_agendada', models.DateTimeField(verbose_name='data agendada')),
            ],
            bases=('manutencao.manutencao',),
        ),
        migrations.CreateModel(
            name='TecnicoResponsavel',
            fields=[
                ('responsavel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manutencao.Responsavel')),
                ('cpf', models.CharField(max_length=11)),
            ],
            bases=('manutencao.responsavel',),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='qualificacoes',
            field=models.ManyToManyField(related_name='qualificados', to='manutencao.Qualificacao'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.Equipamento'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.Responsavel'),
        ),
        migrations.AlterUniqueTogether(
            name='qualificacao',
            unique_together=set([('equipamento', 'tipo')]),
        ),
    ]
